### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by TemKaSD** [punpun1/Ene-Pm#5]
Привет, вот опечатка:

![2017-01-28_105309](https://cloud.githubusercontent.com/assets/6318282/22392685/cd859912-e547-11e6-83e4-540ef5242350.png)

**Comment by Gameerr** [comment]
Принято.

**Comment by mRWiNeT** [comment]
проблема такая: не показывает установленную автатрку(показывает  что нет изображения) и ромбики с вопросами перед ником вверху и перед двое точим. Можно решить это как-то?

**Comment by punpun1** [comment]
Это была не опечатка.
