### ISSUE TITLE
Не выводит смайлы

### ISSUE THREAD

**Issue by iishel2** [punpun1/Ene-Pm#6]
Не выводит смайлы в чате, вместо смайлов вот это:
img src="http://сайт.ru//templates/Default/ene_pm/front_end/emoji/34.png" class="emoji"
img src="http://сайт.ru//templates/Default/ene_pm/front_end/emoji/33.png" class="emoji"
Версия движка 11.3. как решить данную ошибку?

**Comment by punpun1** [comment]
Исправлено.
